import { Metadata } from "next";
import Navbar from "@/Components/Navbar/Navbar";
import "./globals.css";
import BackNavigation from "@/Components/Custom/Util/BackNavigation";

export const metadata: Metadata = {
  title: "Jfarms Project",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-0 p-0 h-screen bg-green-100 dark:bg-green-950 text-black dark:text-slate-200 overflow-x-hidden">
        <Navbar />
        {/* <BackNavigation /> */}
        <main>{children}</main>
        <footer className=" text-center text-xs lg:text-sm mb-2 mt-3">
          ©2023 The JFarms Collective - All rights reserved
        </footer>
      </body>
    </html>
  );
}
