import { Metadata } from "next";
import Navbar from "@/Components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Jfarms Project",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
