import { Metadata } from "next";
import Navbar from "@/Components/Navbar/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jfarms Project",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="m-0 p-0 h-screen bg-white dark:bg-black">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
